// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeting/v2/greeting.proto

package v2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Created              string   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Hostname             string   `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_251d6056f7b1a348, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Greeting) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Greeting) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Greeting) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Greeting) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type GreetingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingRequest) Reset()         { *m = GreetingRequest{} }
func (m *GreetingRequest) String() string { return proto.CompactTextString(m) }
func (*GreetingRequest) ProtoMessage()    {}
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_251d6056f7b1a348, []int{1}
}

func (m *GreetingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingRequest.Unmarshal(m, b)
}
func (m *GreetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingRequest.Marshal(b, m, deterministic)
}
func (m *GreetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingRequest.Merge(m, src)
}
func (m *GreetingRequest) XXX_Size() int {
	return xxx_messageInfo_GreetingRequest.Size(m)
}
func (m *GreetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingRequest proto.InternalMessageInfo

type GreetingResponse struct {
	Greeting             []*Greeting `protobuf:"bytes,1,rep,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GreetingResponse) Reset()         { *m = GreetingResponse{} }
func (m *GreetingResponse) String() string { return proto.CompactTextString(m) }
func (*GreetingResponse) ProtoMessage()    {}
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_251d6056f7b1a348, []int{2}
}

func (m *GreetingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingResponse.Unmarshal(m, b)
}
func (m *GreetingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingResponse.Marshal(b, m, deterministic)
}
func (m *GreetingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingResponse.Merge(m, src)
}
func (m *GreetingResponse) XXX_Size() int {
	return xxx_messageInfo_GreetingResponse.Size(m)
}
func (m *GreetingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingResponse proto.InternalMessageInfo

func (m *GreetingResponse) GetGreeting() []*Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greeting.v2.Greeting")
	proto.RegisterType((*GreetingRequest)(nil), "greeting.v2.GreetingRequest")
	proto.RegisterType((*GreetingResponse)(nil), "greeting.v2.GreetingResponse")
}

func init() { proto.RegisterFile("greeting/v2/greeting.proto", fileDescriptor_251d6056f7b1a348) }

var fileDescriptor_251d6056f7b1a348 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x49, 0xea, 0x4f, 0x9c, 0xa2, 0xd5, 0x81, 0xc2, 0x10, 0x2a, 0x94, 0xac, 0xba, 0x31,
	0x83, 0x11, 0xc4, 0xb5, 0x20, 0xee, 0xeb, 0xce, 0x85, 0x30, 0x49, 0x6e, 0xa7, 0x03, 0x66, 0x6e,
	0x3a, 0x33, 0x0d, 0xb8, 0x15, 0xdf, 0xc0, 0x47, 0xf3, 0x15, 0x7c, 0x10, 0x69, 0xfe, 0x9a, 0x85,
	0xdd, 0xe5, 0xdc, 0xef, 0xdc, 0x70, 0xee, 0x1c, 0x12, 0x4a, 0x03, 0xe0, 0x94, 0x96, 0xbc, 0x4a,
	0x78, 0xf7, 0x1d, 0x97, 0x06, 0x1d, 0xd2, 0x71, 0xaf, 0xab, 0x24, 0x9c, 0x49, 0x44, 0xf9, 0x0e,
	0x5c, 0x94, 0x8a, 0x0b, 0xad, 0xd1, 0x09, 0xa7, 0x50, 0xdb, 0xc6, 0x1a, 0x7d, 0x79, 0x24, 0x78,
	0x6e, 0xdd, 0xf4, 0x82, 0xf8, 0x2a, 0x67, 0xde, 0xdc, 0x5b, 0x9c, 0x2d, 0x7d, 0x95, 0x53, 0x46,
	0x4e, 0x2d, 0x98, 0x4a, 0x65, 0xc0, 0xfc, 0x7a, 0xd8, 0xc9, 0x1d, 0x29, 0xc0, 0x5a, 0x21, 0x81,
	0x8d, 0x1a, 0xd2, 0xca, 0x1d, 0xc9, 0x0c, 0x08, 0x07, 0x39, 0x3b, 0x6a, 0x48, 0x2b, 0x69, 0x48,
	0x82, 0x35, 0x5a, 0xa7, 0x45, 0x01, 0xec, 0xb8, 0x46, 0xbd, 0x8e, 0xae, 0xc8, 0xa4, 0x4b, 0xb1,
	0x84, 0xcd, 0x16, 0xac, 0x8b, 0x9e, 0xc8, 0xe5, 0x7e, 0x64, 0x4b, 0xd4, 0x16, 0xe8, 0x2d, 0x09,
	0xba, 0xd3, 0x98, 0x37, 0x1f, 0x2d, 0xc6, 0xc9, 0x34, 0x1e, 0xdc, 0x1a, 0xf7, 0x0b, 0xbd, 0x2d,
	0xd9, 0xec, 0xff, 0xfc, 0xd2, 0x86, 0x7f, 0x1b, 0x9c, 0x3c, 0xfb, 0x7f, 0xbf, 0xc9, 0x10, 0x5e,
	0x1f, 0xa0, 0x4d, 0x9c, 0x68, 0xfa, 0xf9, 0xf3, 0xfb, 0xed, 0x4f, 0xe8, 0x79, 0xfd, 0xb8, 0x9d,
	0xf5, 0xf1, 0xe1, 0xf5, 0x5e, 0x2a, 0xb7, 0xde, 0xa6, 0x71, 0x86, 0x05, 0x97, 0xc2, 0x7c, 0x58,
	0x27, 0x56, 0x2b, 0x34, 0x39, 0x2f, 0xd3, 0x9b, 0xbe, 0x37, 0x09, 0x9a, 0x4b, 0xe4, 0x83, 0x1e,
	0xd3, 0x93, 0xba, 0x94, 0xbb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0xba, 0x16, 0xda, 0xdd,
	0x01, 0x00, 0x00,
}
